services:
  oak-cuda-dev-env:
    build: .
    container_name: oak-cuda-dev-env
    working_dir: /workspace
    shm_size: "8g"
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/bus/usb:/dev/bus/usb
      - /run/udev:/run/udev:ro
    ports:
      - "8888:8888"
      - "6006:6006"
    environment:
      - PYTHONPATH=/workspace
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute,video
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    gpus: all
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888
      --no-browser --allow-root --NotebookApp.token=
    restart: unless-stopped
